import Contact from '@/components/custom/Contact/index';
import NavFooterWrapper from '@/components/HOC/NavFooterWrapper';
import Navbar from "@/components/Navbar";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "The Elevator Company",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        suppressHydrationWarning
        suppressContentEditableWarning
      >
        <NavFooterWrapper>
            {children}
        </NavFooterWrapper>
      </body>
    </html>
  );
}
